#spring properties
spring:
  profiles: local
  application:
    name: frog-replenish-service
  datasource:
    url: jdbc:mysql://localhost:13306/cdot_elec_frog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: cfrog@1009
#    password: 123456
    #password: chargedot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    redis:
      host: 127.0.0.1
      port: 6379

#eureka config
eureka:
  instance:
    preferIpAddress: true
  client:
    filter-only-up-instances: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
    fetch-registry: true

#server config
server:
  port: 8555

#restTemplate time out config
rest:
  connectionRequestTimeout: 35000
  readTimeout: 35000
  connectTimeout: 35000

#mybatis config
mybatis:
  mapper-locations: classpath:com/chargedot/replenishservice/mapper/*.xml
  type-aliases-package: com.chargedot.replenishservice.model

#logging config
logging:
  level:
    com.chargedot.elecfrogservice.mapper: debug

#hystrix time out config
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql



---
#spring properties
spring:
  profiles: dev
  application:
    name: frog-replenish-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cdot_elec_frog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: chargedot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka config
eureka:
  instance:
    preferIpAddress: true
  client:
    filter-only-up-instances: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
    fetch-registry: true

#server config
server:
  port: 8555

#restTemplate time out config
rest:
  connectionRequestTimeout: 35000
  readTimeout: 35000
  connectTimeout: 35000

#mybatis config
mybatis:
  mapper-locations: classpath:com/chargedot/replenishservice/mapper/*.xml
  type-aliases-package: com.chargedot.replenishservice.model

#logging config
logging:
  level:
    com.chargedot.elecfrogservice.mapper: debug

#hystrix time out config
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

---
#spring properties
spring:
  profiles: test
  application:
    name: frog-replenish-service
  datasource:
    url: jdbc:mysql://172.31.172.141:3306/cdot_elec_frog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: chargedot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka config
eureka:
  instance:
    preferIpAddress: true
  client:
    filter-only-up-instances: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://172.31.172.142:18761/eureka/
    fetch-registry: true

#server config
server:
  port: 8555

#restTemplate time out config
rest:
  connectionRequestTimeout: 35000
  readTimeout: 35000
  connectTimeout: 35000

#mybatis config
mybatis:
  mapper-locations: classpath:com/chargedot/replenishservice/mapper/*.xml
  type-aliases-package: com.chargedot.replenishservice.model

#logging config
logging:
  level:
    com.chargedot.elecfrogservice.mapper: debug

#hystrix time out config
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

---
#spring properties
spring:
  profiles: pro
  application:
    name: frog-replenish-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cdot_elec_frog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: chargedot
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

#eureka config
eureka:
  instance:
    preferIpAddress: true
  client:
    filter-only-up-instances: true
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
    fetch-registry: true

#server config
server:
  port: 8555

#restTemplate time out config
rest:
  connectionRequestTimeout: 35000
  readTimeout: 35000
  connectTimeout: 35000

#mybatis config
mybatis:
  mapper-locations: classpath:com/chargedot/replenishservice/mapper/*.xml
  type-aliases-package: com.chargedot.replenishservice.model

#logging config
logging:
  level:
    com.chargedot.elecfrogservice.mapper: debug

#hystrix time out config
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

